
default: clean setup.cfg setup.py glimpse.i numpy.i glimpse_python.cc glimpse_python.h __init__.py
	./setup.py bdist_wheel

clean:
	rm -rf build dist glimpse.egg-info __pycache__ glimpse.py glimpse_wrap.cpp
